create table public.roles (
  id serial not null,
  name text not null,
  description text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint roles_pkey primary key (id),
  constraint roles_name_key unique (name)
) TABLESPACE pg_default;
-- Default values: INSERT INTO "public"."roles" ("id", "name", "description", "created_at", "updated_at") VALUES ('1', 'Consumer', 'Regular customers who purchase products', '2025-09-04 14:03:04.960544+00', '2025-09-06 01:36:30.523515+00'), ('2', 'Producer', 'Farmers who sell products', '2025-09-04 14:03:04.960544+00', '2025-09-06 01:36:30.523515+00'), ('3', 'Admin', 'System administrators', '2025-09-04 14:03:04.960544+00', '2025-09-06 01:36:30.523515+00');



create table public.statuses (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  category text null,
  constraint user_status_pkey primary key (id),
  constraint user_status_name_key unique (name)
) TABLESPACE pg_default;
-- Default values: INSERT INTO "public"."statuses" ("id", "name", "created_at", "updated_at", "category") VALUES ('1', 'active', '2025-09-05 17:52:13.199562+00', '2025-09-06 01:36:03.312067+00', 'Users & Products'), ('2', 'suspended', '2025-09-05 17:52:26.189327+00', '2025-09-06 01:36:03.312067+00', 'Users & Products'), ('3', 'pending', '2025-09-07 11:35:22.699202+00', '2025-09-07 11:35:22.699202+00', 'Orders'), ('4', 'confirmed', '2025-09-07 11:36:29.529139+00', '2025-09-07 11:36:29.529139+00', 'Orders'), ('5', 'preparing', '2025-09-07 11:36:46.077958+00', '2025-09-07 11:36:46.077958+00', 'Orders'), ('6', 'ready for pickup', '2025-09-07 11:37:11.19451+00', '2025-09-07 11:37:11.19451+00', 'Orders'), ('7', 'completed', '2025-09-07 11:37:27.857148+00', '2025-09-07 11:37:27.857148+00', 'Orders'), ('8', 'cancelled', '2025-09-07 11:37:42.061736+00', '2025-09-07 11:37:42.061736+00', 'Orders');



create table public.categories (
  id serial not null,
  name text not null,
  description text null,
  icon text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint categories_pkey primary key (id),
  constraint categories_name_key unique (name)
) TABLESPACE pg_default;



create table public.payment_methods (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  constraint payment_methods_pkey primary key (id)
) TABLESPACE pg_default;
-- Default values: INSERT INTO "public"."payment_methods" ("id", "name", "created_at", "updated_at") VALUES ('1', 'COD/COP', '2025-09-07 11:25:38.577516+00', '2025-09-07 11:25:38.577516+00'), ('2', 'Online Payment', '2025-09-07 11:26:40.906947+00', '2025-09-07 11:26:40.906947+00');



create table public.delivery_methods (
  id bigint generated by default as identity not null,
  name text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint delivery_methods_pkey primary key (id)
) TABLESPACE pg_default;
-- Default values: INSERT INTO "public"."delivery_methods" ("id", "name", "created_at", "updated_at") VALUES ('1', 'Farm Pickup', '2025-09-07 08:15:29.398818+00', '2025-09-07 08:17:07.376131+00'), ('2', 'Home Delivery', '2025-09-07 08:15:49.026291+00', '2025-09-07 08:17:07.376131+00');



create table public.profiles (
  id uuid not null,
  email text null,
  name text null,
  address text null,
  contact text null,
  avatar_url text null,
  role_id integer null default 1,
  email_verified boolean null default false,
  last_login timestamp with time zone not null default now(),
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  delivery_cost numeric(10, 2) null default 50.0,
  minimum_order_quantity numeric(10, 2) null default 1.0,
  status_id bigint not null default '1'::bigint,
  suspension_reason text null,
  daily_delivery_limit bigint not null default '3'::bigint,
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE,
  constraint profiles_role_id_fkey foreign KEY (role_id) references roles (id),
  constraint profiles_status_id_fkey foreign KEY (status_id) references statuses (id) on update CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_profiles_role_id on public.profiles using btree (role_id) TABLESPACE pg_default;

create index IF not exists idx_profiles_email on public.profiles using btree (email) TABLESPACE pg_default;

create trigger on_profiles_updated BEFORE
update on profiles for EACH row
execute FUNCTION handle_updated_at ();

create trigger protect_profiles_timestamps_trigger BEFORE
update on profiles for EACH row
execute FUNCTION protect_profiles_timestamps ();



create table public.products (
  id serial not null,
  user_id uuid not null,
  name text not null,
  description text null,
  price numeric(10, 2) not null,
  stock numeric(10, 2) null default 0,
  category_id integer null,
  crop_id bigint null,
  image_url text null,
  approval_date timestamp with time zone null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  status_id bigint not null default '1'::bigint,
  rejection_reason text null,
  constraint products_pkey primary key (id),
  constraint products_category_id_fkey foreign KEY (category_id) references categories (id),
  constraint products_crop_id_fkey foreign KEY (crop_id) references crops (id) on update CASCADE on delete set null,
  constraint products_status_id_fkey foreign KEY (status_id) references statuses (id) on update CASCADE,
  constraint products_user_id_fkey foreign KEY (user_id) references profiles (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_products_farmer_id on public.products using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_products_category_id on public.products using btree (category_id) TABLESPACE pg_default;

create index IF not exists idx_products_created_at on public.products using btree (created_at desc) TABLESPACE pg_default;

create trigger on_products_updated BEFORE
update on products for EACH row
execute FUNCTION handle_updated_at ();



create table public.orders (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  delivery_method_id bigint not null,
  payment_method_id bigint not null,
  status_id bigint not null default '3'::bigint,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  seller_id uuid not null,
  delivery_fee_at_order numeric not null default '0'::numeric,
  order_notes text null,
  constraint orders_pkey primary key (id),
  constraint orders_delivery_method_id_fkey foreign KEY (delivery_method_id) references delivery_methods (id) on update CASCADE on delete RESTRICT,
  constraint orders_payment_method_id_fkey foreign KEY (payment_method_id) references payment_methods (id) on update CASCADE on delete RESTRICT,
  constraint orders_seller_id_fkey foreign KEY (seller_id) references profiles (id) on update CASCADE on delete set null,
  constraint orders_status_id_fkey foreign KEY (status_id) references statuses (id) on update CASCADE on delete RESTRICT,
  constraint orders_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;



create table public.order_items (
  id bigint generated by default as identity not null,
  order_id bigint not null,
  product_id integer null,
  name_at_purchase text not null,
  quantity numeric not null,
  price_at_purchase numeric not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  request_replacement_reason text null,
  request_replacement_image_url text null,
  constraint order_items_pkey primary key (id),
  constraint order_items_order_id_fkey foreign KEY (order_id) references orders (id) on update CASCADE on delete CASCADE,
  constraint order_items_product_id_fkey foreign KEY (product_id) references products (id) on update CASCADE on delete set null
) TABLESPACE pg_default;



create table public.favorites (
  id serial not null,
  user_id uuid null,
  product_id integer null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint favorites_pkey primary key (id),
  constraint favorites_user_id_product_id_key unique (user_id, product_id),
  constraint favorites_product_id_fkey foreign KEY (product_id) references products (id) on delete CASCADE,
  constraint favorites_user_id_fkey foreign KEY (user_id) references profiles (id) on delete CASCADE
) TABLESPACE pg_default;



create table public.carts (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  status_id bigint not null default '1'::bigint,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint carts_pkey primary key (id),
  constraint carts_user_id_key unique (user_id),
  constraint carts_status_id_fkey foreign KEY (status_id) references statuses (id) on update CASCADE,
  constraint carts_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;



create table public.cart_items (
  id serial not null,
  product_id integer null,
  quantity numeric(10, 2) not null default 1.0,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  cart_id bigint not null,
  constraint cart_items_pkey primary key (id),
  constraint cart_items_cart_id_fkey foreign KEY (cart_id) references carts (id) on update CASCADE on delete CASCADE,
  constraint cart_items_product_id_fkey foreign KEY (product_id) references products (id) on delete CASCADE
) TABLESPACE pg_default;

create trigger on_cart_items_updated BEFORE
update on cart_items for EACH row
execute FUNCTION handle_updated_at ();

create table public.crops (
  id bigint generated by default as identity not null,
  name text not null,
  category_id integer null,
  market_demand text not null,
  growing_season text not null,
  harvest_time text not null,
  icon text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  description text null,
  min_price numeric not null default '0'::numeric,
  max_price numeric not null default '0'::numeric,
  constraint crops_pkey primary key (id),
  constraint crops_category_id_fkey foreign KEY (category_id) references categories (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.planted_crops (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  crop_id bigint not null,
  is_harvested boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint planted_crops_pkey primary key (id),
  constraint planted_crops_crop_id_fkey foreign KEY (crop_id) references crops (id) on update CASCADE on delete CASCADE,
  constraint planted_crops_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.farming_guides (
  id bigint generated by default as identity not null,
  name text not null,
  description text null,
  url text not null,
  crop_id bigint null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint farming_guides_pkey primary key (id),
  constraint farming_guides_crop_id_fkey foreign KEY (crop_id) references crops (id) on update CASCADE on delete set default
) TABLESPACE pg_default;

create table public.conversations (
  id bigint generated by default as identity not null,
  consumer_id uuid not null,
  producer_id uuid not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint conversations_pkey primary key (id),
  constraint conversations_consumer_id_fkey foreign KEY (consumer_id) references profiles (id) on update CASCADE on delete CASCADE,
  constraint conversations_producer_id_fkey foreign KEY (producer_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.messages (
  id bigint generated by default as identity not null,
  conversation_id bigint not null,
  sender_id uuid not null,
  body text not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  is_read boolean not null default false,
  constraint messages_pkey primary key (id),
  constraint messages_conversation_id_fkey foreign KEY (conversation_id) references conversations (id) on update CASCADE on delete CASCADE,
  constraint messages_sender_id_fkey foreign KEY (sender_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.seller_applications (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  valid_id_url text not null,
  farming_experience text not null,
  rejection_reason text null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint seller_applications_pkey primary key (id),
  constraint seller_applications_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.application_crops (
  id bigint generated by default as identity not null,
  application_id bigint not null,
  crop_id bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint application_crops_pkey primary key (id),
  constraint application_crops_application_id_fkey foreign KEY (application_id) references seller_applications (id) on update CASCADE on delete CASCADE,
  constraint application_crops_crop_id_fkey foreign KEY (crop_id) references crops (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.suspended_products (
  id bigint generated by default as identity not null,
  product_id integer not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint suspended_products_pkey primary key (id),
  constraint suspended_products_product_id_fkey foreign KEY (product_id) references products (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.reviews (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  product_id integer not null,
  review text null,
  rating numeric not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  image_url text null,
  constraint reviews_pkey primary key (id),
  constraint reviews_product_id_fkey foreign KEY (product_id) references products (id) on update CASCADE on delete CASCADE,
  constraint reviews_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.helpful_reviews (
  id bigint generated by default as identity not null,
  user_id uuid not null,
  review_id bigint not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint helpful_reviews_pkey primary key (id),
  constraint helpful_reviews_review_id_fkey foreign KEY (review_id) references reviews (id) on update CASCADE on delete CASCADE,
  constraint helpful_reviews_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.reported_reviews (
  id bigint generated by default as identity not null,
  user_id uuid null,
  review_id bigint null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint reported_reviews_pkey primary key (id),
  constraint reported_reviews_review_id_fkey foreign KEY (review_id) references reviews (id) on update CASCADE on delete CASCADE,
  constraint reported_reviews_user_id_fkey foreign KEY (user_id) references profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;